name: "Qualcomm PR email addresses checker"
description: "Validate each commit's author/committer email addresses are appropriate for the repo"

runs:
  using: "composite"
  steps:
    - name: Check emails
      id: check_emails
      shell: bash
      run: ${GITHUB_ACTION_PATH}/check_email_pr.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PULL_NUMBER: ${{ github.event.number }}
        COMMITS_COUNT: ${{ github.event.pull_request.commits }}
