name: CI

on:
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "check_email_pr.sh"
      - ".github/workflows/ci.yml"
  push:
    paths:
      - "src/**"
      - "test/**"
      - "check_email_pr.sh"
      - ".github/workflows/ci.yml"

jobs:
  email_check_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        shell: bash
        run: ./check_email_pr.sh --test
